[Serverless] Added serverless practices
wizelineacademy/BAZJAVASR5-2023 pull request #2
Opened 2023-05-28 13:08 UTC by Ciul

## Qué archivos revisar?

Los ejercicios agregados en la ruta `Semana 1/Serverless/Practicas`

2023-05-28 13:14 UTC, Ciul commented
@gruizest

2023-05-29 17:04 UTC, Wizeline-GerardoRuiz requested changes
Por favor elimina los archivos .DS_Store que están en el repositorio

2023-05-29 17:04 UTC, Wizeline-GerardoRuiz commented on Semana 1/Serverless/Practicas/2-cajero-automatico-step-functions/.DS_Store
Por favor elimina este archivo

2023-05-29 17:04 UTC, Wizeline-GerardoRuiz commented on Semana 1/Serverless/Practicas/2-cajero-automatico-step-functions/csharp/.DS_Store
Por favor elimina este archivo

2023-05-29 17:04 UTC, Wizeline-GerardoRuiz commented on Semana 1/Serverless/Practicas/2-cajero-automatico-step-functions/csharp/lambda-fns/.DS_Store
Por favor elimina este archivo

2023-05-29 17:04 UTC, Wizeline-GerardoRuiz commented on Semana 1/Serverless/Practicas/2-cajero-automatico-step-functions/python/.DS_Store
Por favor elimina este archivo

2023-05-29 17:04 UTC, Wizeline-GerardoRuiz commented on Semana 1/Serverless/Practicas/2-cajero-automatico-step-functions/python/lambda_fns/.DS_Store
Por favor elimina este archivo

2023-05-29 17:04 UTC, Wizeline-GerardoRuiz commented on Semana 1/Serverless/Practicas/2-cajero-automatico-step-functions/typescript/.DS_Store
Por favor elimina este archivo

2023-05-29 17:04 UTC, Wizeline-GerardoRuiz commented on Semana 1/Serverless/Practicas/2-cajero-automatico-step-functions/typescript/lambda-fns/.DS_Store
Por favor elimina este archivo

2023-05-29 17:04 UTC, Wizeline-GerardoRuiz commented on Semana 1/Serverless/Practicas/3-cron-jobs-con-eventbridge/.DS_Store
Por favor elimina este archivo

2023-05-29 17:04 UTC, Wizeline-GerardoRuiz commented on Semana 1/Serverless/Practicas/3-cron-jobs-con-eventbridge/csharp/.DS_Store
Por favor elimina este archivo

2023-05-29 17:04 UTC, Wizeline-GerardoRuiz commented on Semana 1/Serverless/Practicas/3-cron-jobs-con-eventbridge/java/.DS_Store
Por favor elimina este archivo

2023-05-29 17:04 UTC, Wizeline-GerardoRuiz commented on Semana 1/Serverless/Practicas/3-cron-jobs-con-eventbridge/python/.DS_Store
Por favor elimina este archivo

2023-05-29 17:04 UTC, Wizeline-GerardoRuiz commented on Semana 1/Serverless/Practicas/3-cron-jobs-con-eventbridge/typescript/.DS_Store
Por favor elimina este archivo

2023-05-29 17:04 UTC, Wizeline-GerardoRuiz commented on Semana 1/Serverless/Practicas/4-rds-proxy/.DS_Store
Por favor elimina este archivo

2023-05-29 17:04 UTC, Wizeline-GerardoRuiz commented on Semana 1/Serverless/Practicas/4-rds-proxy/python/.DS_Store
Por favor elimina este archivo

2023-05-29 17:04 UTC, Wizeline-GerardoRuiz commented on Semana 1/Serverless/Practicas/4-rds-proxy/typescript/.DS_Store
Por favor elimina este archivo

2023-05-29 17:04 UTC, Wizeline-GerardoRuiz commented on Semana 1/Serverless/Practicas/5-patron-webservice/.DS_Store
Por favor elimina este archivo

2023-05-29 17:04 UTC, Wizeline-GerardoRuiz commented on Semana 1/Serverless/Practicas/5-patron-webservice/csharp/.DS_Store
Por favor elimina este archivo

2023-05-29 17:04 UTC, Wizeline-GerardoRuiz commented on Semana 1/Serverless/Practicas/5-patron-webservice/java/.DS_Store
Por favor elimina este archivo

2023-05-29 17:04 UTC, Wizeline-GerardoRuiz commented on Semana 1/Serverless/Practicas/5-patron-webservice/python/.DS_Store
Por favor elimina este archivo

2023-05-29 17:04 UTC, Wizeline-GerardoRuiz commented on Semana 1/Serverless/Practicas/5-patron-webservice/typescript/.DS_Store
Por favor elimina este archivo

2023-05-29 17:04 UTC, Wizeline-GerardoRuiz commented on Semana 1/Serverless/Practicas/6-patron-lambdaless/.DS_Store
Por favor elimina este archivo

2023-05-29 17:04 UTC, Wizeline-GerardoRuiz commented on Semana 1/Serverless/Practicas/6-patron-lambdaless/python/.DS_Store
Por favor elimina este archivo

2023-05-29 17:04 UTC, Wizeline-GerardoRuiz commented on Semana 1/Serverless/Practicas/6-patron-lambdaless/typescript/.DS_Store
Por favor elimina este archivo

2023-05-30 16:41 UTC, Wizeline-GerardoRuiz approved these changes
LGTM, I'll remove the extra files 👍

2023-05-30 16:51 UTC, merged